// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6HAoiAOtBZW6Cdthn6pbUV-OW3fEocuo',
    appId: '1:1000026424654:web:943c194549d15426d08a1f',
    messagingSenderId: '1000026424654',
    projectId: 'study-gachon',
    authDomain: 'study-gachon.firebaseapp.com',
    storageBucket: 'study-gachon.firebasestorage.app',
    measurementId: 'G-BSFB60FFWF',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgUdJpzeoAWQtk1ups3uPmVOvhlJvdJhg',
    appId: '1:1000026424654:ios:42d9c79dff331dfed08a1f',
    messagingSenderId: '1000026424654',
    projectId: 'study-gachon',
    storageBucket: 'study-gachon.firebasestorage.app',
    iosBundleId: 'com.example.studyWith',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgUdJpzeoAWQtk1ups3uPmVOvhlJvdJhg',
    appId: '1:1000026424654:ios:42d9c79dff331dfed08a1f',
    messagingSenderId: '1000026424654',
    projectId: 'study-gachon',
    storageBucket: 'study-gachon.firebasestorage.app',
    iosBundleId: 'com.example.studyWith',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6HAoiAOtBZW6Cdthn6pbUV-OW3fEocuo',
    appId: '1:1000026424654:web:97b66d6af9e74360d08a1f',
    messagingSenderId: '1000026424654',
    projectId: 'study-gachon',
    authDomain: 'study-gachon.firebaseapp.com',
    storageBucket: 'study-gachon.firebasestorage.app',
    measurementId: 'G-N9898J1Y3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_VYnVvxMsPU_YNe-H2mNbN4Em3ApH4ik',
    appId: '1:1000026424654:android:66a62c5a1a0d1b51d08a1f',
    messagingSenderId: '1000026424654',
    projectId: 'study-gachon',
    storageBucket: 'study-gachon.firebasestorage.app',
  );

}