name: Deploy Flutter Web and Firebase Functions

on:
  push:
    branches:
      - main

jobs:
  # Flutter 웹 앱 배포 Job
  build-and-deploy-web:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      # 3. Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # 4. Build the Flutter web app
      - name: Build Web
        run: flutter build web --release

      # 5. Create a CNAME file for the custom domain
      - name: Create CNAME file
        run: echo "studywith.online" > ./build/web/CNAME  # replace with your actual domain

      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.STUDYWITH }}
          publish_dir: ./build/web
          publish_branch: gh-pages

  # Firebase Functions 배포 Job
  deploy-functions:
    runs-on: ubuntu-latest
    needs: build-and-deploy-web  # 웹 앱 배포 후 실행

    steps:
      # 1. Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 4. Authenticate Firebase CLI
      - name: Authenticate Firebase CLI
        run: firebase login:ci --token ${{ secrets.FIREBASE_TOKEN }}

      # 5. Deploy Firebase Functions
      - name: Deploy Functions
        run: firebase deploy --only functions
